from __future__ import annotations

from typing import Any
import numpy as np

# This file is generated from funcs_numba.py.
# Do not edit manually.

def get_row_hashes(x: 'np.ndarray') -> 'np.ndarray': ...
def get_box_tallies(box_ids: 'np.ndarray', hashes: 'np.ndarray') -> 'np.ndarray': ...
def get_box_count(data: 'np.ndarray', scale: 'float') -> 'int': ...
def get_bounded_idxs(data: Any, scales: Any, lower_bound: 'int | None' = None, upper_bound: 'int | None' = None) -> 'tuple[int | None, int | None, int | None, int | None]': ...
def is_nearly_monotonic(y: 'np.ndarray', *, direction: 'str' = 'decreasing', tolerance: 'float' = 0.02) -> 'bool': ...
def compute_deshmukh_slope_estimate(trimmed_scales: 'np.ndarray', trimmed_H: 'np.ndarray', deshmukh_reg_proportion: 'float', error_eps: 'float' = 1e-06) -> 'float | None': ...
def simple_linear_regression(x: Any, y: Any) -> Any: ...

__all__: list[str]
