from __future__ import annotations

from typing import Any, Literal
import numpy as np

# This file is generated from kernels_numba.py.
# Do not edit manually.

def get_row_hashes(x: 'np.ndarray') -> 'np.ndarray': ...
def get_box_tallies(box_ids: 'np.ndarray', hashes: 'np.ndarray') -> 'np.ndarray': ...
def get_box_count(data: 'np.ndarray', scale: 'float') -> 'int': ...
def get_bounded_idxs(data: Any, scales: Any, lower_bound: 'int | None' = None, upper_bound: 'int | None' = None) -> 'tuple[int | None, int | None, int | None, int | None]': ...
def is_nearly_monotonic(y: 'np.ndarray', *, direction: 'str' = 'decreasing', tolerance: 'float' = 0.02) -> 'bool': ...
def compute_deshmukh_slope_estimate(trimmed_scales: 'np.ndarray', trimmed_H: 'np.ndarray', deshmukh_reg_proportion: 'float', averaging_method: Literal['mean', 'median', 'modalmean', 'modalmax'] = 'mean', error_eps: 'float' = 1e-06) -> 'float | None': ...
def simple_linear_regression(x: 'np.ndarray', y: 'np.ndarray') -> 'tuple[float, float]': ...
def get_row_hashes_numba(x: 'np.ndarray') -> 'np.ndarray': ...
def get_box_tallies_numba(box_ids: 'np.ndarray', hashes: 'np.ndarray') -> 'np.ndarray': ...
def get_box_count_numba(data: 'np.ndarray', scale: 'float') -> 'int': ...
def get_bounded_idxs_numba(data: Any, scales: Any, lower_bound: 'int | None' = None, upper_bound: 'int | None' = None) -> 'tuple[int | None, int | None, int | None, int | None]': ...
def is_nearly_monotonic_numba(y: 'np.ndarray', *, direction: 'str' = 'decreasing', tolerance: 'float' = 0.02) -> 'bool': ...
def compute_deshmukh_slope_estimate_numba(trimmed_scales: 'np.ndarray', trimmed_H: 'np.ndarray', deshmukh_reg_proportion: 'float', averaging_method: Literal['mean', 'median', 'modalmean', 'modalmax'] = 'mean', error_eps: 'float' = 1e-06) -> 'float | None': ...
def simple_linear_regression_numba(x: 'np.ndarray', y: 'np.ndarray') -> 'tuple[float, float]': ...

__all__: list[str]