from __future__ import annotations

from typing import Any
from types import ModuleType
import numpy as np

# This file is generated from kernels_numba.py.
# Do not edit manually.

def jit_module(**kwargs: Any) -> Any: ...
def _install_numba_funcs(module: ModuleType, install_failbacks: bool) -> None: ...
def _get_row_hashes(x: 'np.ndarray') -> 'np.ndarray': ...
def _get_box_tallies(box_ids: 'np.ndarray', hashes: 'np.ndarray') -> 'np.ndarray': ...
def _array_equal(x: 'np.ndarray', y: 'np.ndarray') -> Any: ...
def _get_box_count(data: 'np.ndarray', scale: 'float') -> 'int': ...
def _get_bounded_idxs(data: Any, scales: Any, lower_bound: 'int | None' = None, upper_bound: 'int | None' = None) -> 'tuple[int | None, int | None, int | None, int | None]': ...
def _trim_extreme_slopes(alphas: 'np.ndarray', breakpoints: 'np.ndarray', max_slope: 'float') -> 'tuple[np.ndarray, np.ndarray]': ...
def _is_nearly_monotonic(y: 'np.ndarray', *, direction: 'str' = 'decreasing', tolerance: 'float' = 0.02) -> 'bool': ...
def _compute_deshmukh_slope_estimate(trimmed_scales: 'np.ndarray', trimmed_H: 'np.ndarray', deshmukh_reg_proportion: 'float', error_eps: 'float' = 1e-06) -> 'float | None': ...
def _simple_linear_regression(x: Any, y: Any) -> Any: ...
def _get_row_hashes_numba(x: 'np.ndarray') -> 'np.ndarray': ...
def _get_box_tallies_numba(box_ids: 'np.ndarray', hashes: 'np.ndarray') -> 'np.ndarray': ...
def _array_equal_numba(x: 'np.ndarray', y: 'np.ndarray') -> Any: ...
def _get_box_count_numba(data: 'np.ndarray', scale: 'float') -> 'int': ...
def _get_bounded_idxs_numba(data: Any, scales: Any, lower_bound: 'int | None' = None, upper_bound: 'int | None' = None) -> 'tuple[int | None, int | None, int | None, int | None]': ...
def _trim_extreme_slopes_numba(alphas: 'np.ndarray', breakpoints: 'np.ndarray', max_slope: 'float') -> 'tuple[np.ndarray, np.ndarray]': ...
def _is_nearly_monotonic_numba(y: 'np.ndarray', *, direction: 'str' = 'decreasing', tolerance: 'float' = 0.02) -> 'bool': ...
def _compute_deshmukh_slope_estimate_numba(trimmed_scales: 'np.ndarray', trimmed_H: 'np.ndarray', deshmukh_reg_proportion: 'float', error_eps: 'float' = 1e-06) -> 'float | None': ...
def _simple_linear_regression_numba(x: Any, y: Any) -> Any: ...

__all__: list[str]
