from __future__ import annotations

import numpy as np
import copy
import gc

from abc import ABC
from typing import TYPE_CHECKING

from pyspoc._base import Component

if TYPE_CHECKING:
    from pyspoc.statistic import Statistic


class Reducer(Component, ABC):

    _cached_results: dict[Statistic, dict[Reducer, np.ndarray]] = dict()

    def calculate(self,
                  statistic: Statistic) -> np.ndarray:

        # temporarily uncache results, TODO: fix caching mechanisms
        self.uncache(statistic)

        statistic_results = self._cached_results.get(statistic)

        if statistic_results is not None:
            result = statistic_results.get(self)

            if result is not None:
                return result

        statistic_result = statistic.get_result()
        statistic_result_cp = copy.deepcopy(statistic_result) # NOTE: Check if this is still required.
        #statistic_result_cp = np.atleast_3d(statistic_result_cp)
        #statistic_sliced = self._slice_data(statistic_result_cp)
        result = self.compute(statistic_result_cp)
        result = np.array(result)

        if statistic_results is None:
            self._cached_results[statistic] = {
                self: result
            }
        else:
            statistic_results[self] = result

        return result
    
    def compute(self, data: np.ndarray) -> np.ndarray | float:
        """
        Compute the reduction method on the statistical data provided.

        Parameters
        ----------

        data: numpy.ndarray
            A numpy array generated by a Statistic.

        Returns
        ----------
        numpy.array or float
            Reduction of the statistic as either a vector or scalar value.

        """
        return super().compute(data)

    @classmethod
    def uncache(cls, statistic: Statistic, include_gc: bool = False):
        cached_statistic_results = cls._cached_results.get(statistic)

        if cached_statistic_results:
            cls._cached_results[statistic] = dict()

        if include_gc:
            gc.collect()

    @staticmethod
    def _slice_data(data: np.ndarray):
        return data[:, :, 0]

    @staticmethod
    def _get_component_type() -> type:
        return Reducer
