# This file is generated by scripts/generate_rstatistics_stub.py.
# It gives static analysis tools explicit names for runtime-discovered exports.

from pyspoc.rstatistics.fractal.main import GeneralizedEntropy
from pyspoc.rstatistics.norms import (
    EntryWiseMatrixNorm,
    Norm,
    SchattenNorm,
)
from pyspoc.rstatistics.pca import (
    PCAEigenVectors,
    PCAVarianceExplainedRatio,
)
from pyspoc.rstatistics.ranks import (
    EffectiveRank,
    StableRank,
)

__all__ = [
    "EffectiveRank",
    "EntryWiseMatrixNorm",
    "GeneralizedEntropy",
    "Norm",
    "PCAEigenVectors",
    "PCAVarianceExplainedRatio",
    "SchattenNorm",
    "StableRank",
]
