from __future__ import annotations

import warnings
import numpy as np
import gc

from abc import ABC, abstractmethod
from typing import final, Generic, TypeVar

from pyspoc.core._component import Component
from pyspoc._caching.reducer import reducer_result_cache
from pyspoc.core.statistic._base import Statistic
from pyspoc.core.types import (
    NumpyFloatCubicTensor1DTo2D,
    NumpyFloatCubicTensorUpTo1D,
)
from pyspoc.dataset import Dataset
from pyspoc.settings import settings
    

ReducerInputT = TypeVar("ReducerInputT", bound=NumpyFloatCubicTensor1DTo2D, contravariant=True)
ReducerOutputT = TypeVar("ReducerOutputT", bound=NumpyFloatCubicTensorUpTo1D, covariant=True)


class Reducer(Component, Generic[ReducerInputT, ReducerOutputT], ABC):

    @final
    def calculate_reduction(
            self,
            dataset: Dataset,
            statistic: Statistic) -> ReducerOutputT:

        if settings.current.reducer_caching:
            cached_result = reducer_result_cache.get(self, statistic, dataset)

            if cached_result is not None:
                return cached_result

        statistic_result = statistic.calculate_summary(dataset)
        
        with warnings.catch_warnings(record=True) as captured:
            warnings.simplefilter("always")
            result = self.reduce(statistic_result)

            if captured and self._active_calculator is not None:
                self._active_calculator._add_warnings(captured)

        result = self._prepare_component_result(result)

        if settings.current.reducer_caching:
            reducer_result_cache.store(
                self,
                statistic,
                dataset,
                result,
                settings.current.max_reducer_cache_memory_fraction,
            )

        return result
    
    
    def reduce(
        self,
        data: ReducerInputT) -> ReducerOutputT:
        """
        Compute the reduction method on the statistical data provided.

        Parameters
        ----------

        data: numpy.ndarray
            A numpy array generated by a Statistic.

        Returns
        ----------
        numpy.array or float
            Reduction of the statistic as either a vector or scalar value.

        """

        # NumPy's native generic annotation communicates rank and dtype to
        # static tooling, but Typeguard does not currently enforce those
        # parameters at runtime. Preserve the public contract explicitly at
        # this boundary before concrete numerical code receives the input.
        if not isinstance(data, np.ndarray):
            raise TypeError(
                f"{self.__class__.__name__} {self.name} received invalid data type. "
                "Input data must be a NumPy array.")
        
        if data.ndim != 1 and data.ndim != 2:
            raise ValueError(
                f"{self.__class__.__name__} {self.name} received invalid data shape. "
                f"Input data must be one- or two-dimensional, but got shape {data.shape}."
            )
        
        if not np.issubdtype(data.dtype, np.floating):
            raise TypeError(
                f"{self.__class__.__name__} {self.name} received invalid Numpy dtype. "
                f"Input data must have a floating dtype, but got {data.dtype}."
            )

        # Compute the statistic and return.
        result = self._reduce(data)

        # Perform validation based on Statistic return type.
        result = self._get_validated_result(result)

        return result

    @final
    @classmethod
    def clear_cache(cls, dataset: Dataset, include_gc: bool = False):
        reducer_result_cache.clear_dataset(dataset)

        if include_gc:
            gc.collect()


    @abstractmethod
    def _reduce(
            self,
            data: ReducerInputT) -> ReducerOutputT:
        pass


    @abstractmethod
    def _get_validated_result(
        self,
        result: NumpyFloatCubicTensor1DTo2D) -> ReducerOutputT:
        """Validate and return a value produced by :meth:`_reduce`.

        Parameters
        ----------
        result : :class:`NumpyFloatCubicTensor1DTo2D`
            Candidate statistic result. It must be a cubic float tensor with
            one or two dimensions, hence the following results are accepted:
            - a `float` vector: a one-dimensional Numpy array of
                :class:`np.floating` dtype.
            - a `float` square matrix: a two-dimensional Numpy array of
                :class:`np.floating` dtype with equal row and column counts.

        Returns
        -------
        :class:`NumpyFloatCubicTensor1DTo2D`
            The original result, unchanged, after successful validation.

        Raises
        ------
        TypeCheckError
            If ``result`` is not Numpy cubic tensor with one or two dimensions.

        Notes
        -----
        This method is deliberately an identity operation. Its purpose is to
        provide a stable runtime-validation boundary after a concrete
        :meth:`_reduce` implementation returns. Subclasses can override it
        with narrower jaxtyping annotations and additional semantic checks,
        calling ``super()._get_validated_result(result)`` to retain the base
        contract.
        """
        pass
    

    @staticmethod
    def _get_component_type() -> type:
        return Reducer
