from __future__ import annotations

import argparse
import importlib
import sys
from collections import defaultdict
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_NAME = "pyspoc.rstatistics"
STUB_PATH = REPO_ROOT / "pyspoc" / "rstatistics" / "__init__.pyi"


def _load_rstatistics_module():
    """Load pyspoc.rstatistics from the working tree."""
    if sys.version_info < (3, 10):
        version = ".".join(str(part) for part in sys.version_info[:3])
        raise SystemExit(
            f"{PACKAGE_NAME} requires Python 3.10 or newer; current interpreter is {version}."
        )

    sys.path.insert(0, str(REPO_ROOT))
    return importlib.import_module(PACKAGE_NAME)


def _render_stub() -> str:
    rstatistics = _load_rstatistics_module()
    classes = rstatistics._REDUCED_STATISTIC_CLASSES

    imports_by_module: dict[str, list[str]] = defaultdict(list)
    for class_name, class_obj in sorted(classes.items()):
        imports_by_module[class_obj.__module__].append(class_name)

    lines = [
        "# This file is generated by scripts/generate_rstatistics_stub.py.",
        "# It gives static analysis tools explicit names for runtime-discovered exports.",
        "",
    ]

    for module_name, class_names in sorted(imports_by_module.items()):
        if len(class_names) == 1:
            class_name = class_names[0]
            #lines.append(f"from {module_name} import {class_name} as {class_name}")
            lines.append(f"from {module_name} import {class_name}")
        else:
            lines.append(f"from {module_name} import (")
            #lines.extend(f"    {class_name} as {class_name}," for class_name in class_names)
            lines.extend(f"    {class_name}," for class_name in class_names)
            lines.append(")")

    all_names = sorted(classes)
    lines.extend(
        [
            "",
            "__all__ = [",
            *(f'    "{class_name}",' for class_name in all_names),
            "]",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate pyspoc.rstatistics stub exports for type checkers."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with an error if the existing stub is out of date.",
    )
    args = parser.parse_args()

    stub_text = _render_stub()

    if args.check:
        existing_text = STUB_PATH.read_text(encoding="utf-8") if STUB_PATH.exists() else None
        if existing_text != stub_text:
            raise SystemExit(f"{STUB_PATH.relative_to(REPO_ROOT)} is out of date.")
        return

    STUB_PATH.write_text(stub_text, encoding="utf-8")
    print(f"Wrote {STUB_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
